version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - apt-get update && apt-get install -y maven
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 586928288932.dkr.ecr.us-east-1.amazonaws.com

  pre_build:
    commands:
      - echo Building JAR file...
      - mvn clean package -DskipTests

  build:
    commands:
      - IMAGE_TAG=586928288932.dkr.ecr.us-east-1.amazonaws.com/awspringbootdeployment-app:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo Building Docker image $IMAGE_TAG...
      - docker build -t $IMAGE_TAG .
      - echo Pushing Docker image to ECR...
      - docker push $IMAGE_TAG

artifacts:
  files:
    - '**/*'

